### ISSUE TITLE
Soil Reference page no longer available

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/sheets_and_friends#119]
![image](https://user-images.githubusercontent.com/7374085/165181385-609af8b2-e584-4c23-9de7-1c2e23f67d97.png)

Clicking on "Soil Reference" button opens a new window pointing to [this URL](https://deploy-preview-101--voluble-pika-79eed4.netlify.app/template/soil_emsl_jgi_mg/reference.html), which shows the following error page:

![image](https://user-images.githubusercontent.com/7374085/165181014-3a5d55e0-2f73-4134-a8ff-231e965ef95e.png)

Need to figure out who can help fix this.

FYI: @subdavis @turbomam

**Comment by pkalita-lbl** [comment]
I can take a look

**Comment by turbomam** [comment]
I'll add some notes here

**Comment by turbomam** [comment]
[Pajau (she/her)](https://app.slack.com/team/UNRMT87GR)
I’m seeing that the reference HTML link is broken. since @subdavis  also reported this, I presume this might be a problem further upstream? do you want me to create an issue in sheets and friends?

@turbomam 
Yeah, I have a bad feeling it's just not supported in DH yet.  I'm not sure what the best short term solution is.

I think the issue here is that the tempalte generation code used to operate over a single tempalte at a. time and create a single reference HTML. Now it operates over a single input at a time, and can define multiple templates from the multiple classes in a LinkML file. It can also be run incrementally, adding templates after the fact.

So @damion asked whether there should be one reference HTML per template (probably) or one per LinkML input.

**Comment by ddooley** [comment]
Right #304 fixes this by making reference guide auto-generated from schema rather than as a static .html file. I just merged the fix to that as well so this should be resolved with latest linkml-datastructure branch.

**Comment by pkalita-lbl** [comment]
With this commit https://github.com/microbiomedata/nmdc-server/commit/892b7e7ea0d5ac94f40d6cff5b611792f198389c the new auto-generated reference pages are being used in the NMDC portal. I think we're ready to close this one.
