### ISSUE TITLE
Re-visit the ENVO drop downs for the soil package.

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/sheets_and_friends#133]
2/3 terms that were entered for the SPRUCE data on the data portal aren’t in the drop downs

**Comment by turbomam** [comment]
This issue is about making it easier for NMDC curators to build environment-specific lists of EnvO terms that are suitable for env_broad_scale, env_local_scale and env_medium

Will bootstrap from a combination of the branch of EnvO specified by MIxS (theoretical) repaired findings from the INSDC SQLite database (empirical), and previous curations

Principal tool: ontology access kit

Output: three spreadsheets, with EnvO terms as rows and enviroment packages as columns. Curators will just have to tick off the compatible combinations.

**Comment by turbomam** [comment]
@mslarae13 @pvangay or others: where can I find the original Google Sheets in which NMDC colleagues recorded the term/enviroment curations?

**Comment by turbomam** [comment]
@ssarrafan @mslarae13 Moved discussion of this issue to [dh_testing](https://github.com/microbiomedata/dh_testing), especially the README.md. We have many issues and documents addressing this topic, and I will be adding links to those in the dh_testing README.md.
