### ISSUE TITLE
"geographic location (country and/or sea,region)" no longer checks formatting

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/sheets_and_friends#67]
Entering in "CO", "Colorado", or any text validates successfully. I recalled this particular term used to have more complex checks for formatting, i.e. looked for colons.

![image](https://user-images.githubusercontent.com/7374085/155244917-4c1b5692-0755-4321-8397-1c495ce2c852.png)

**Comment by turbomam** [comment]
Actually, I [don't think I ever did implement a validation](https://docs.google.com/spreadsheets/d/1RACmVPhqpfm2ELm152CzmiEy2sDmULmbN9G0qXK8NDs/edit#gid=928747012&range=28:28) for this because MIxS provides a string serialization of `{term}: {term}, {text}` and I never felt like I understood the difference between `{term}` and `{text}`. Especially considering MIxS uses a similar serialization of `{termLabel} {[termID]}` for the environmental triad terms.

I think the idea is that the first two portions of `geo_loc_name` "geographic location (country and/or sea,region)" are supposed to use a controlled vocabulary, enforcing things like "USA" but not accepting "US" or "America". I just don't think I can implement that in DH right now, so I'll treat it like `{text}: {text}, {text}`

**Comment by turbomam** [comment]
^ that will make it a MIxS modified term

**Comment by turbomam** [comment]
Let's try this regular expression: `^[^:, ][^:]*: [^:, ][^,]*, [^:, ].*$`
